# Generated by Django 4.2.3 on 2023-07-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('testId', models.AutoField(primary_key=True, serialize=False)),
                ('score1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='점수1')),
                ('score2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='점수2')),
                ('score3', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='점수3')),
                ('score4', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='점수4')),
                ('score5', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='점수5')),
                ('score6', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='점수6')),
                ('score7', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='점수7')),
                ('score8', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='점수8')),
                ('score9', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='점수9')),
                ('score10', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='점수10')),
            ],
        ),
    ]
