# Generated by Django 4.2.3 on 2023-07-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savescore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='test_type',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='검사종류1~4'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='점수1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score10',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='점수10'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='점수2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='점수3'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='점수4'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='점수5'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='점수6'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='점수7'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score8',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='점수8'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score9',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='점수9'),
        ),
    ]
